---

  - name: Install docker dependencies
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
      state: present

  - name: Install docker-ce
    yum:
      name: "docker-ce-{{ docker_version }}"
      state: present
      allow_downgrade: yes
    notify: "restart docker"

  - name: Install docker python (as required by docker_login)
    pip:
      name: docker
      state: present

  - name: Configure docker data dir and storage driver
    lineinfile:
      dest: /usr/lib/systemd/system/docker.service
      regexp: "^ExecStart=/usr/bin/dockerd"
      line: "ExecStart=/usr/bin/dockerd -g {{ docker_data_dir }} --storage-driver {{ docker_storage_driver }}"
    notify: "restart docker"

  - name: "Ensure {{ docker_data_dir }} exists"
    file:
      name: "{{ docker_data_dir }}"
      state: directory
    notify: "restart docker"

# TODO: ansible doesn't force deletion of folder when creating a symlink, only a file.
# Folder has to be removed manually.
  - name: "Ensure {{ docker_data_dir }} exists"
    file:
      src: "{{ docker_data_dir }}"
      dest: "/var/lib/docker"
      state: link
      force: yes
    when: docker_data_dir != "/var/lib/docker"
    notify: "restart docker"

  - name: Ensure docker starts at next reboot
    service:
      name: docker
      enabled: true

  - meta: flush_handlers
